# Generated by Django 5.0.3 on 2024-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/profiles/%pk'),
        ),
    ]
