# Generated by Django 5.0.3 on 2024-04-25 20:07

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_profile_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(blank=True, default='', upload_to=authors.models.user_directory_path),
        ),
    ]
